package com.acepero13.android.gamereviewer.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Code
import androidx.compose.material.icons.outlined.ContentCopy
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.SheetState
import androidx.compose.material3.Switch
import androidx.compose.material3.SwitchDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.OutlinedButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.acepero13.chess.core.ui.theme.ChessGold
import com.acepero13.chess.core.ui.theme.LocalAppColors

private val DevBg     = Color(0xFF0D1117)  // code box stays dark for readability
private val DevBorder = Color(0xFF30363D)
private val DevLabel  = Color(0xFF79C0FF)

private const val EVAL_INSTRUCTIONS = """You are a chess coach evaluator. I will give you a position and a coaching comment generated by an automated chess review app. Your job is to judge whether the coaching comment is accurate, relevant, and pedagogically sound for the given position.

---

"""

private const val EVAL_QUESTIONS = """

---

## What I want you to evaluate

Answer each of the following five questions with a short paragraph (3–5 sentences max).
End with an overall verdict: ✅ Accurate | ⚠️ Partially accurate | ❌ Inaccurate.

1. **Trigger accuracy** — Is the coaching trigger type correct for this position?
   Given the position and the centipawn swing, was this the right *type* of moment to flag?

2. **Description accuracy** — Is the description factually correct for this specific position?
   Does it describe what is actually happening on the board, or is it generic/misleading?

3. **Question relevance** — Are the three questions useful guides toward the actual best move?
   Would answering them lead a player to find (or understand) the correct idea?

4. **Hint quality** — Is the conceptual hint accurate and does it avoid giving away the engine line?
   Is it the right level of abstraction (concept, not move)?

5. **Overall verdict** — Rate the coaching output as a whole.
   Would this comment genuinely help an improving player understand what went wrong?"""

/**
 * Bottom sheet shown when the developer taps the bug-report FAB on the analysis screen.
 *
 * Displays the filled-in coach-accuracy evaluation prompt.  A toggle lets the user
 * include or exclude the static LLM instructions so they can copy just the raw data
 * when they already have the system prompt loaded in their LLM session.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DevCoachPromptSheet(
    dataSection: String,
    sheetState:  SheetState,
    onCopy:      (text: String) -> Unit,
    onDismiss:   () -> Unit,
    modifier:    Modifier = Modifier,
) {
    var includeInstructions by remember { mutableStateOf(true) }
    val appColors = LocalAppColors.current

    val displayedText = if (includeInstructions) {
        EVAL_INSTRUCTIONS + dataSection + EVAL_QUESTIONS
    } else {
        dataSection
    }

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState       = sheetState,
        containerColor   = appColors.surface,
        contentColor     = appColors.textPrimary,
        modifier         = modifier,
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp)
                .padding(bottom = 24.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp),
        ) {
            // ── Header ─────────────────────────────────────────────────────────
            Row(verticalAlignment = Alignment.CenterVertically) {
                Icon(
                    imageVector        = Icons.Outlined.Code,
                    contentDescription = null,
                    tint               = DevLabel,
                    modifier           = Modifier.size(18.dp),
                )
                Spacer(Modifier.width(8.dp))
                Text(
                    text       = "Coach Accuracy Prompt",
                    style      = MaterialTheme.typography.titleSmall,
                    fontWeight = FontWeight.Bold,
                    color      = DevLabel,
                )
            }
            Text(
                text  = "Paste into an LLM to verify coaching accuracy.",
                style = MaterialTheme.typography.bodySmall,
                color = appColors.textPrimary.copy(alpha = 0.6f),
            )

            HorizontalDivider(color = appColors.border)

            // ── Instructions toggle ────────────────────────────────────────────
            Row(
                modifier              = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment     = Alignment.CenterVertically,
            ) {
                Column(modifier = Modifier.weight(1f)) {
                    Text(
                        text       = "Include evaluation instructions",
                        style      = MaterialTheme.typography.bodySmall,
                        fontWeight = FontWeight.SemiBold,
                        color      = appColors.textPrimary,
                    )
                    Text(
                        text  = "Prepends the system prompt and appends the 5 evaluation questions",
                        style = MaterialTheme.typography.labelSmall,
                        color = appColors.textPrimary.copy(alpha = 0.5f),
                    )
                }
                Spacer(Modifier.width(12.dp))
                Switch(
                    checked         = includeInstructions,
                    onCheckedChange = { includeInstructions = it },
                    colors          = SwitchDefaults.colors(
                        checkedThumbColor  = DevBg,
                        checkedTrackColor  = DevLabel,
                        uncheckedTrackColor = DevBorder,
                    ),
                )
            }

            HorizontalDivider(color = appColors.border)

            // ── Prompt text box ────────────────────────────────────────────────
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(320.dp)
                    .clip(RoundedCornerShape(8.dp))
                    .background(DevBg)
                    .padding(12.dp),
            ) {
                Text(
                    text     = displayedText,
                    style    = MaterialTheme.typography.bodySmall.copy(
                        fontFamily = FontFamily.Monospace,
                        fontSize   = 11.sp,
                        lineHeight = 17.sp,
                    ),
                    color    = Color(0xFFE6EDF3),  // always light text in dark code box
                    modifier = Modifier.verticalScroll(rememberScrollState()),
                )
            }

            // ── Actions ────────────────────────────────────────────────────────
            Row(
                modifier              = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
            ) {
                OutlinedButton(
                    onClick  = { onCopy(displayedText) },
                    modifier = Modifier.weight(1f),
                ) {
                    Icon(
                        Icons.Outlined.ContentCopy, null,
                        modifier = Modifier.size(16.dp),
                        tint     = ChessGold,
                    )
                    Spacer(Modifier.width(6.dp))
                    Text("Copy to clipboard", color = ChessGold, fontWeight = FontWeight.SemiBold)
                }
                TextButton(onClick = onDismiss) {
                    Text("Close", color = appColors.textPrimary.copy(alpha = 0.6f))
                }
            }
        }
    }
}
